services:
  web:
    build: ./app
    platform: linux/amd64
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.docker
    depends_on:
      - db
  db:
    image: postgres:18.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./app/.env.docker
  mkdocs:
    image: hackforlaops/mkdocs:latest
    command: mkdocs serve --dev-addr 0.0.0.0:8000
    ports:
      - 8005:8000
    volumes:
      - .:/app

volumes:
  postgres_data:
